/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoscrum;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Santi
 */
public class VentanaNuevoElemento extends javax.swing.JFrame {

    private Proyecto p;
    private VentanaElemetos f;
    /**
     * Creates new form VentanaNuevoElemento
     */
    public VentanaNuevoElemento(Proyecto p, VentanaElemetos f) {
        this.p = p;
        this.f = f;
        initComponents();
        this.jLabelFRelacionados2.setVisible(false);
        this.jLabelDElementales2.setVisible(false);
        this.jTextFieldFRelacionados2.setVisible(false);
        this.jTextFieldDElementales2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelTipo = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabelFrelacionados1 = new javax.swing.JLabel();
        jLabelDElementales1 = new javax.swing.JLabel();
        jTextFieldFrelacionados1 = new javax.swing.JTextField();
        jTextFieldDElementales1 = new javax.swing.JTextField();
        jLabelFRelacionados2 = new javax.swing.JLabel();
        jLabelDElementales2 = new javax.swing.JLabel();
        jTextFieldFRelacionados2 = new javax.swing.JTextField();
        jTextFieldDElementales2 = new javax.swing.JTextField();
        jButtonAnadir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir Nuevo Elemento");

        jLabelNombre.setText("Nombre del Elemento:");

        jLabelTipo.setText("Tipo:");

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EE", "SE", "CE", "FLI", "FLE" }));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });

        jLabelFrelacionados1.setText("Nº Ficheros Relacionados:");

        jLabelDElementales1.setText("Nº Datos Elementales:");

        jLabelFRelacionados2.setText("Nº Ficheros Relacionados S:");

        jLabelDElementales2.setText("Nº Datos Elementales S:");

        jTextFieldFRelacionados2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFRelacionados2ActionPerformed(evt);
            }
        });

        jButtonAnadir.setText("Añadir Elemento");
        jButtonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelFrelacionados1)
                                    .addComponent(jLabelDElementales1))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldFrelacionados1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDElementales1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonAnadir))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelDElementales2)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelFRelacionados2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDElementales2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFRelacionados2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTipo)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFrelacionados1)
                    .addComponent(jTextFieldFrelacionados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDElementales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDElementales1))
                .addGap(8, 8, 8)
                .addComponent(jButtonAnadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFRelacionados2)
                    .addComponent(jTextFieldFRelacionados2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDElementales2)
                    .addComponent(jTextFieldDElementales2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        String tipo = (String) this.jComboBoxTipo.getSelectedItem();
        switch (tipo) {
            case "EE":
            case "SE":
                this.jLabelFRelacionados2.setVisible(false);
                this.jLabelDElementales2.setVisible(false);
                this.jTextFieldFRelacionados2.setVisible(false);
                this.jTextFieldDElementales2.setVisible(false);
                this.jLabelFrelacionados1.setText("Nº Ficheros referenciados:");
                this.jLabelDElementales1.setText("Nº Datos Elementales:");
                break;
            case "CE":
                this.jLabelFRelacionados2.setVisible(true);
                this.jLabelDElementales2.setVisible(true);
                this.jTextFieldFRelacionados2.setVisible(true);
                this.jTextFieldDElementales2.setVisible(true);
                this.jLabelFrelacionados1.setText("Nº Ficheros referenciados E:");
                this.jLabelDElementales1.setText("Nº Datos Elementales E:");
                break;
            case "FLI":
            case "FLE":
                this.jLabelFRelacionados2.setVisible(false);
                this.jLabelDElementales2.setVisible(false);
                this.jTextFieldFRelacionados2.setVisible(false);
                this.jTextFieldDElementales2.setVisible(false);
                this.jLabelFrelacionados1.setText("Nº Registros:");
                this.jLabelDElementales1.setText("Nº Datos Elementales:");
                break;
        }
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jTextFieldFRelacionados2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFRelacionados2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFRelacionados2ActionPerformed

    private void jButtonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirActionPerformed
        try {
            Elemento e;
            
            for(Elemento temp : p.getElementos()) {
                if(temp.getNombre().equalsIgnoreCase(this.jTextFieldNombre.getText())) {
                    JOptionPane.showMessageDialog(null,"Nombre ya existente en la base de datos de elementos.");
                    return;
                }
            }
            
            if(Integer.parseInt(this.jTextFieldFrelacionados1.getText()) < 0 || Integer.parseInt(this.jTextFieldDElementales1.getText()) < 0){
                throw new Exception();
            }
            
            if(!((String) this.jComboBoxTipo.getSelectedItem()).equalsIgnoreCase("CE")) {
                e = new Elemento(this.jTextFieldNombre.getText(), (String)this.jComboBoxTipo.getSelectedItem(), Integer.parseInt(this.jTextFieldFrelacionados1.getText()), Integer.parseInt(this.jTextFieldDElementales1.getText()));
            } else {
                e = new Elemento(this.jTextFieldNombre.getText(), (String)this.jComboBoxTipo.getSelectedItem(), Integer.parseInt(this.jTextFieldFrelacionados1.getText()), Integer.parseInt(this.jTextFieldDElementales1.getText()), Integer.parseInt(this.jTextFieldFRelacionados2.getText()), Integer.parseInt(this.jTextFieldDElementales2.getText()));
            }
            e.calcularComplejidad();
            p.anadirElemento(e);
            p.calcularPFNA();
            p.calcularPFA();
            f.actualizarElementos();
            this.dispose();
        } catch(Exception E) {
            JOptionPane.showMessageDialog(null,"Error a la hora de introducir los datos");
        }
    }//GEN-LAST:event_jButtonAnadirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnadir;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabelDElementales1;
    private javax.swing.JLabel jLabelDElementales2;
    private javax.swing.JLabel jLabelFRelacionados2;
    private javax.swing.JLabel jLabelFrelacionados1;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JTextField jTextFieldDElementales1;
    private javax.swing.JTextField jTextFieldDElementales2;
    private javax.swing.JTextField jTextFieldFRelacionados2;
    private javax.swing.JTextField jTextFieldFrelacionados1;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
